# Задача 2.3. KNN

В этом задании Вам предлагается написать класс `KNN_classifier`, пригодный для решения задачи классификации (многоклассовой).

Мы предлагаем Вам шаблон класса. В этом шаблоне заполните тела функций `.fit` и `.predict`

В качестве функции близости используйте Евклидово расстояние между объектами (подробнее https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).

Напоминание:

* Функция `.fit(x, y)` производит обучение модели. В рамках этой функции необходимо реализовать подбор оптимальных параметров модели/сконфигурировать модель для дальнейшего использования на основе данной тренировочной выборки, где x - это матрица признакового описания выборки, а y - вектор ответов.

* Функция `.predict(x)` осуществляет предсказание для каждого из объектов, чьи векторные описания представлены строками матрицы x. Выполняется строго после `.fit()`. Ради безопасности можно даже реализовать механизм отказа в виде выбрасывания специальной ошибки `UnfittedError` в случае попытки вызова функции `.predict()` до вызова функции `.fit()`.

Замечание: не изменяйте названия класса и его методов. Это приведёт к ошибке при исполнении Вашего кода в процессе проверки задания. Тем не менее, Вы можете дописать свои собственные методы, если это необходимо.

Шаблон класса:

In [ ]:
import numpy as np


class KNN_classifier:
    def __init__(self, n_neighbors: int, **kwargs):
        self.K = n_neighbors
        self.X_train = None
        self.y_train = None

    def fit(self, x: np.array, y: np.array):
        self.X_train = x
        self.y_train = y

    def predict(self, x: np.array):
        if self.X_train is None or self.y_train is None:
            raise ValueError("Модель не обучена. Пожалуйста, вызовите метод fit перед predict.")

        predictions = []
        for sample in x:
            distances = np.sqrt(np.sum((self.X_train - sample) ** 2, axis=1))
            nearest_indices = np.argsort(distances)[:self.K]
            nearest_labels = self.y_train[nearest_indices]
            prediction = np.argmax(np.bincount(nearest_labels))
            predictions.append(prediction)
        return np.array(predictions)

## Примечания

1. Вы можете проверить правильность выполнения задания посредством сравнения полученных результатов с функцией из соответствующего модуля `sklearn`.

2. В рамках выполнения данного задания **запрещено** использовать функции из пакета `sklearn` и любого другого, кроме `numpy`. Код, использующий любые другие модули, не пройдёт тесты.

3. **Подсказка:** если Вы испытываете сложности с реализацией этого задания, начните выполнять его с написания функции `.predict`. В процессе написания этой функции Вы поймёте, что конкретно Вам требуется получить от обучающей выборки, какую информацию и в каком видед извлечь из неё. Затем реализуйте это в функции `.fit`

*Курсив*## Пример входных и выходных данных

In [ ]:
X

NameError: ignored

In [ ]:
y

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
knn = KNN_classifier(n_neighbors=3)

In [ ]:
knn.fit(X, y)

In [ ]:
x_test

array([[-0.12489725,  0.65791923, -0.73112495,  1.42660225,  1.64728976],
       [ 0.01913388, -1.11351208, -0.63244098, -0.98121107,  0.38060892],
       [-0.92074931,  1.39812225,  0.39692147,  0.7717827 ,  0.44604002]])

In [ ]:
knn.predict(x_test)

array([1, 0, 0])